package com.example.myproject.navigation

const val ROUTE_HOME = "home"
const val ROUTE_SIGNUP = "signup"
const val ROUTE_LOGIN = "login"
//const val ROUTE_DASHBOARD = "dashboard"
//const val ROUTE_CALL= "call"
//const val ROUTE_LOCATION= "location"
const val ROUTE_JOURNAL= "journal"
const val ROUTE_CREATE = "create"
const val ROUTE_VIEW_CREATE = "view_create"
//const val ROUTE_FRONT = "frontpage"
//const val ROUTE_SURVIVORS = "survivors"
//const val ROUTE_PROFILE = "profile"
const val ROUTE_LOGOUT = "logout"
const val ROUTE_VIEW_UPLOAD = "upload"
//const val ROUTE_VIEW_LOCATION = "location"
//const val ROUTE_UPDATE_LOCATION = "update_location"
const val ROUTE_UPDATE_CREATE = "update_create"
//const val ROUTE_ABOUT = "about"
//const val ROUTE_CONTACT = "contact"
//const val ACCESS_FINE_LOCATION = "location"
//const val ACCESS_COURSE_LOCATION = "location"